apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp  # Correctly indented under selector
  ports:                           # Correctly indented under spec
    - protocol: TCP
      port: 80
      targetPort: 9376
